name: Run Tests
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
  workflow_dispatch:
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'

      - name: Run Python generator tests
        run: python -m unittest discover tests/static/ -p "test_generate.py"

      - name: Run JS UI tests
        run: node tests/static/test_app.js

  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - '8.1'
          - '8.2'
          - '8.3'
          - '8.4'
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # 2.36.0
        with:
          php-version: ${{ matrix.php-versions }}
          tools: php-cs-fixer

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run linter (php-cs-fixer)
        run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer --diff --dry-run -v fix

      - name: Run tests
        run: |
          vendor/atoum/atoum/bin/atoum -d tests/units/ --use-light-report
          php tests/integrity/source_integrity.php
          php tests/functional/test.php
