name: Update locales
on:
  schedule:
    - cron: '0 8 * * 1-5' #  At 8:00 on every Monday
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'

      - name: Run update scripts
        run: |
          pip install toml
          python app/scripts/bugzilla_query.py
          python app/scripts/update_sources.py

      - run : git config --global user.email 'flodolo@users.noreply.github.com'
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          commit-message: "Update locales"
          branch-suffix: "timestamp"
          title: "Update locales"
